<article><h1>Profil</h1><hr><br>
<div class="berita">
    <br>
    <h2><a href="#" alt="#" class="judul">Profil Departemen Agama</a></h2>
<hr>
<br>
<p class="isi" style="font-size:14px;">
Bangsa Indonesia adalah bangsa yang religius. Hal tersebut tercermin baik dalam kehidupan bermasyarakat maupun dalam kehidupan bernegara. Di lingkungan masyarakat-terlihat terus meningkat kesemarakan dan kekhidmatan kegiatan keagamaan baik dalam bentuk ritual, maupun dalam bentuk sosial keagamaan. Semangat keagamaan tersebut, tercermin pula dalam kehidupan bernegara yang dapat dijumpai dalam dokumen-dokumen kenegaraan tentang falsafah negara Pancasila, UUD 1945, GBHN, dan buku Repelita serta memberi jiwa dan warna pada pidato-pidato kenegaraan.<br><br>
Dalam pelaksanaan pembangunan nasional semangat keagamaan tersebut menj adi lebih kuat dengan ditetapkannya asas keimanan dan ketaqwaan terhadap Tuhan yang Maha Esa sebagai salah satu asas pembangunan. Hal ini berarti bahwa segala usaha dan kegiatan pembangunan nasional dijiwai, digerakkan dan dikendalikan oleh keimanan dan ketaqwaan terhadap Tuhan Yang Maha Esa sebagai nilai luhur yang menjadi landasan spiritual, moral dan etik pembangunan.<br><br>
Secara historis benang merah nafas keagamaan tersebut dapat ditelusuri sejak abad V Masehi, dengan berdirinya kerajaan Kutai yang bercorak Hindu di Kalimantan melekat pada kerajaan-kerajaan di pulau Jawa, antara lain kerajaan Tarumanegara di Jawa Barat, dan kerajaan Purnawarman di Jawa Tengah.<br><br>
Pada abad VIII corak agama Budha menjadi salah satu ciri kerajaan Sriwijaya yang pengaruhnya cukup luas sampai ke Sri Lanka, Thailand dan India. Pada masa Kerajaan Sriwijaya, candi Borobudur dibangun sebagai lambang kejayaan agama Budha. Pemerintah kerajaan Sriwijaya juga membangun sekolah tinggi agama Budha di Palembang yang menjadi pusat studi agama Budha se-Asia Tenggara pada masa itu. Bahkan beberapa siswa dari Tiongkok yang ingin memperdalam agama Budha lebih dahulu beberapa tahun membekali pengetahuan awal di Palembang sebelum melanjutkannya ke India.<br><br>
Menurut salah satu sumber Islam mulai memasuki Indonesia sejak abad VII melalui para pedagang Arab yang telah lama berhubungan dagang dengan kepulauan Indonesia tidak lama setelah Islam berkembang di jazirah Arab. Agama Islam tersiar secara hampir merata di seluruh kepulauan nusantara seiring dengan berdirinya kerajaan-kerajaan Islam seperti Perlak dan Samudera Pasai di Aceh, kerajaan Demak, Pajang dan Mataram di Jawa Tengah, kerajaan Cirebon dan Banten di Jawa Barat, kerajaan Goa di Sulawesi Selatan, keraj aan Tidore dan Ternate di Maluku, keraj aan Banjar di Kalimantan, dan lain-lain.<br><br>
Dalam sejarah perjuangan bangsa Indonesia menentang penjajahan Belanda banyak raja dan kalangan bangsawan yang bangkit menentang penjajah. Mereka tercatat sebagai pahlawan bangsa, seperti Sultan Iskandar Muda, Teuku Cik Di Tiro, Teuku Umar, Cut Nyak Dien, Panglima Polim, Sultan Agung Mataram, Imam Bonjol, Pangeran Diponegoro, Sultan Agung Tirtayasa, Sultan Hasanuddin, Sultan Goa, Sultan Ternate, Pangeran Antasari, dan lain-lain. Pola pemerintahan kerajaan-kerajaan tersebut diatas pada umumnya selalu memiliki dan melaksanakan fungsi sebagai berikut:
Fungsi pemerintahan umum, hal ini tercermin pada gelar "Sampean Dalem Hingkang Sinuhun" sebagai pelaksana fungsi pemerintahan umum.<br><br>
Fungsi pemimpin keagamaan tercermin pada gelar "Sayidin Panatagama Kalifatulah."
Fungsi keamanan dan pertahanan, tercermin dalam gelar raja "Senopati Hing Ngalogo." Pada masa penjajahan Belanda sejak abad XVI sampai pertengahan abad XX pemerintahan Hindia Belanda juga "mengatur" pelayanan kehidupan beragama. Tentu saja "pelayanan" keagamaan tersebut tak terlepas dari kepentingan strategi kolonialisme Belanda. Dr.C. Snuck Hurgronye, seorang penasehat pemerintah Hindia Belanda dalam bukunya "Nederland en de Islam" (Brill, Leiden 1911) menyarankan sebagai berikut:<br><br><br>

"Sesungguhnya menurut prinsip yang tepat, campur tangan pemerintah dalam bidang agama adalah salah, namun jangan dilupakan bahwa dalam sistem (tata negara) Islam terdapat sejumlah permasalahan yang tidak dapat dipisahkan hubungannya dengan agama yang bagi suatu pemerintahan yang baik, sama sekali tidak boleh lalai untuk mengaturnya."<br><br>
Pokok-pokok kebijaksanaan pemerintah Hindia Belanda di bidang agama adalah sebagai berikut:
Bagi golongan Nasrani dijamin hak hidup dan kedaulatan organisasi agama dan gereja, tetapi harus ada izin bagi guru agama, pendeta dan petugas misi/zending dalam melakukan pekerjaan di suatu daerah tertentu.<br><br>
Bagi penduduk pribumi yang tidak memeluk agama Nasrani, semua urusan agama diserahkan pelaksanaan dan perigawasannya kepada para raja, bupati dan kepala bumiputera lainnya.
Berdasarkan kebijaksanaan tersebut, pelaksanaannya secara teknis dikoordinasikan oleh beberapa instansi di pusat yaitu:<br><br>
Soal peribadatan umum, terutama bagi golongan Nasrani menjadi wewenang Departement van Onderwijs en Eeredienst (Departemen Pengajaran dan Ibadah)<br>
Soal pengangkatan pejabat agama penduduk pribumi, soal perkawinan, kemasjidan, haji, dan lainlain, menjadi urusan Departement van Binnenlandsch Bestuur (Departemen Dalam Negeri).
Soal Mahkamah Islam Tinggi atau Hofd voor Islamietische Zaken menjadi wewenang Departement van Justitie (Departemen Kehakiman). Pada masa penjajahan Jepang kondisi tersebut pada dasarnya tidak berubah. Pemerintah Jepang membentuk Shumubu, yaitu kantor agama pusat yang berfungsi sama dengan Kantoor voor Islamietische Zaken dan mendirikan Shumuka, kantor agama karesidenan, dengan menempatkan tokoh pergerakan Islam sebagai pemimpin kantor. Penempatan tokoh pergerakan Islam tersebut merupakan strategi Jepang untuk menarik simpati umat Islam agar mendukung cita-cita persemakmuran Asia Raya di bawah pimpinan Dai Nippon.<br>
Secara filosofis, sosio politis dan historis agama bagi bangsa Indonesia sudah berurat dan berakar dalam kehidupan bangsa. Itulah sebabnya para tokoh dan pemuka agama selalu tampil sebagai pelopor pergerakan dan perjuangan kemerdekaan baik melalui partai politik maupun sarana lainnya. Perjuangan gerakan kemerdekaan tersebut melalui jalan yang panjang sejak jaman kolonial Belanda sampai kalahnya Jepang pada Perang Dunia ke II. Kemerdekaan Indonesia diproklamasikan pada tanggal 17 Agustus 1945. Pada masa kemerdekaan kedudukan agama menjadi lebih kokoh dengan ditetapkannya Pancasila sebagai ideologi dan falsafah negara dan UUD 1945.<br><br> Sila Ketuhanan Yang Maha Esa yang diakui sebagai sumber dari sila-sila lainnya mencerminkan karakter bangsa Indonesia yang sangat religius dan sekaligus memberi makna rohaniah terhadap kemajuankemajuan yang akan dicapai. Berdirinya Departemen Agama pada 3 Januari 1946, sekitar lima bulan setelah proklamasi kemerdekaan kecuali berakar dari sifat dasar dan karakteristik bangsa Indonesia tersebut di atas juga sekaligus sebagai realisasi dan penjabaran ideologi Pancasila dan UUD 1945. Ketentuan juridis tentang agama tertuang dalam UUD 1945 BAB E pasal 29 tentang Agama ayat 1, dan 2:<br><br>

    Negara berdasarkan atas Ketuhanan Yang Maha Esa;<br>
Negara menjamin kemerdekaan tiap-tiap penduduk untuk memeluk agamanya masing-masing dan beribadah menurut agamanya dan kepercayaannya itu.Dengan demikian agama telah menjadi bagian dari sistem kenegaraan sebagai hasil konsensus nasional dan konvensi dalam_praktek kenegaraan Republik Indonesia yang berdasarkan Pancasila dan UUD 1945.</p>
<br>
<hr>
<a href='#' class="disabled" style="color:black;">Dibuat Oleh : Admin | Tanggal : 17-08-2017'</a>

    </div>

</article>

